name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          lfs: 'true'
          submodules: 'recursive'
          fetch-depth: '0'
      - 
        name: Checkout LFS objects
        run: git lfs pull; git submodule foreach --recursive git lfs pull
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.16.x'
      - 
        name: Generate version header
        run: |
          cd deps/allonet
          git fetch --tags
          cd ../..
          mkdir build
          cd build
          cmake ..
          make version_header
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: alloverse/alloplace2:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
